apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: null
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: dig-viewer
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dig-viewer
  subjects:
    - kind: ServiceAccount
      name: dig-viewer
      namespace: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: dig-viewer
    namespace: default
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: dig-viewer
  rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
kind: List
metadata: {}
